export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';

export const PAUSE_PLAYER = 'PAUSE_PLAYER';
export const SKIP_TRACK = 'SKIP_TRACK';
export const GET_PLAYER_INFO = 'GET_PLAYER_INFO';
export const SET_VOLUME = 'SET_VOLUME';
export const SEEK = 'SEEK';
export const GET_AUDIO_FEATURES = 'GETTING_AUDIO_FEATURES';
export const GET_AUDIO_ANALYSIS = 'ANALYZING_AUDIO';
export const AUDIO_ANALYZED = 'AUDIO_ANALYZED';
